Fix device missing in OElli.py
Without this, training will be crash
"
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
"